### ISSUE TITLE
Launch 7z2hashcat.exe on Win32

### ISSUE THREAD

**Issue by zvonko1980** [philsmd/7z2hashcat#11]
The program does not work in Win32

**Comment by philsmd** [comment]
yeah, that is very likely that 32bit versions of windows do not work with the exe.

I don't think that this is very often the case that users run 7z2hashcat on 32bit windows versions.

The solution is to just install and run perl manually and run the perl script directly.

The problem with 32bit support is that it could make the release version much larger (it is already about 5MB, that's a lot, most of it is just the perl interpreter) or the script/exe much slower.

What do you think? I think it is very easy to run perl directly with 32bit versions of windows and it is not worth the effort/speed drop/huge file size.

**Comment by zvonko1980** [comment]
I just could not run the script after installing Perl.
The script is not run, since it is necessary to install Compress-Raw-Lzma. I failed to do it :( Can you tell me how to do it...

**Comment by philsmd** [comment]
The readme already explains this:
quote: Perl module "Compress::Raw::Lzma" is required

So you need to install Compress::Raw::Lzma
I think it should work like this: 
`perl -MCPAN -e 'install Compress::Raw::Lzma'`

or if you want to use cpan.exe directly:
`cpan Compress::Raw::Lzma`

Of course this depends on which perl interpreter you have installed etc... please refer to the installation instruction of your perl interpreter.

**Comment by philsmd** [comment]
The newest release version adds also support for 32-bit windows systems as described here: https://github.com/philsmd/7z2hashcat/releases/tag/1.1

To run the 32 bit version you need to download the latest 7z2hashcat32*.zip file and extract the 7z2hashcat32*.exe file (the star, *, here means that the actual file name does depend on the 7z2hashcat version you are trying to download/run, e.g. 1.1 at the time of this post).

Thanks
