### ISSUE TITLE
7za hashes not working with hashcat

### ISSUE THREAD

**Issue by qiangzhuang** [philsmd/7z2hashcat#13]
Use 7za (not 7z) on either Linux or Mac to create an archive such as `7za a -p b.7z filename`. Notice that hashcat is unable to load the hash generated by 7z2hashcat.

./hashcat64.bin -D 1,2 -a 0 -m 11600 ../craphash /home/user/Top258Million-probable.txt
hashcat (v3.6.0-172-g5437de75) starting...

* Device #2: This hardware has outdated CUDA compute capability (3.7).
             For modern OpenCL performance, upgrade to hardware that supports
             CUDA compute capability version 5.0 (Maxwell) or higher.
nvmlDeviceGetFanSpeed(): Not Supported

OpenCL Platform #1: Intel(R) Corporation
========================================
* Device #1: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz, 15352/61410 MB allocatable, 4MCU

OpenCL Platform #2: NVIDIA Corporation
======================================
* Device #2: Tesla K80, 2859/11439 MB allocatable, 13MCU

Hashfile '../craphash' on line 1 ($7z$2$19$0$$8$ece0752bf5bae72a0000000000000000$2396202190$274160$274153$1e45be06092c1becf2772774d4648556a86390256ab07700759ed1b90712d84ff53d4248dec29b960574297cd3a0541ab18ec4907f416fbdc130caece41032d5e063ef49e07057116b8def9e5801bfe6190c9507dcb2bb69d588f75b2b246f4c28c4fe14ba387959f5ff1840fa410f07c0c7ea82bb9ff21d2f2aba1f690406dbac54c915094092388ef10213369d813c35490a7f27ba5829dd636ca37341fc6390f91ad374a69525fee0db243f058655d28a677fbd6109afb7b436ba170a60084f166d31d592ffb4d2759870be47d9598932faffd4e32064eb486e8c08854ead09ced07965988e490a9d5dc561f317622bff93c6bf7322f734d58355dbe57f04112f1fe267874ac0a51d53a65d9679f4191e3605e21da8c2e9b93f78b21bdefea07223e102d4ed27cea660502c03598b98d2580c2e48c555aa177e0bf8644d2d73c67d451e0b06dea667e5b5a602d5db3da73afd24b6c069542fdd61283d4b0384465ad97ccc16eb8226e0c058073af93d7a9064f304311ac4f0e8c9038ac19ca38984b1c79cfb24e8fc6cb4bf86d7c3e546d8439039e7914e70041be43fed73a9f1a8bce43b3be642bdf1361ad1f8bb40576a9798317312b278c075162772d1a087d869ae3ffa6615339e64f03cb135e6b6bb6c3043d2fcc943c63ef65af13a6db3009450d5c2dfe096fdc34b831c5435af61e952450f4585fd29038be8087a15efb3bdb0975b9f4be2a9d52f19d49af8454c0657c2b26ad4a3ed76013fc0188a19ee1fd154ae25f39de6b0a8975793197f9dc46ae5963132bf71616289bbfbe76c7086a6b5b183a1564e49a9ec31aad98c951851e6e1692b0053086edaee6931b06c6582286aed816e2282bb12f0c339c5e2874801821b28962a3e6420720a9b15528c387d79642a97375c05c2b8aa8fac20bb6845de9da5de0fe127dc43d75aff1d1c8a49a4fb7dd856d6fdcbe33fd545ab1e1aaacff381f3eb602809a1ac19ccb8cbc788efeb24f52ff7a442d58cc32ec5a5eabb616ee4fa2756cccccac34a722bbea43ea130f51bc1af80459a7b48f14cb17717fad79381d5926c7f8a7e3aea54b3fc2163473ff4e4bd644ef764cbd0dbd3869e84fa4d849c89cc21ca501122e74bd7fbb6c9df5c16a14d5a5790ad62bcea43fd27cbe44c9e4a8fdc3e5c67cd67ed9881c4bc24e9f27dfc6ffcf6fbfd70c9847f80d51214761962c26bd01ee6d74d18cbd845205766caa632b0f5bc6ed91252edc42fda10ef3a656a2590b701c9f9ef7e1d06859e55475b587714f7bdc8bd7bebe5762c90a2297a2736421a7cc1da446ede48b9819ca763416ac1fb8bacec970974b0d67f3a9b9b5070f51687edd104b6dbf8b5d75f0f0cc09201e0ffc5f1c0d4822841cc91359b1f88e9d65bbf5ebfda3c6ab8f615c0963577257191a984f47863c275541479c33cb56175d00107911a8e15910986f3a4fc8f515c12ac9b5673acaa332bdc7ca48a691ffdc45e44ea2c4ac7fd7c83ab7f1341d9b0aaecb764ff998948eb5f899fb865f6d752559193e170528aeeb656ab7e18c050ebaa3386b46f58d4cd0088b42667ffb430e9cb780f57ab39e3c938a4d58a5089a91dfde82046e57a055f21db794a6aa283b0ce81c50038c7cb5ffdcfc7ba5df3fc278d78ea33ac0e296922d8831d334243d084e847b4bc1074f5c533b7a9dd8ff496a7f666db2aad51f43f647e99c3099797decc6d747e955ba90f13f1f59ede76651c6feecef209542c8f067551dd8e95c0c25f1c8b1f9c98ac62ef0efdcf548e7348219d2fa74f89b5f560c248592fd5f65f8dd2fa506413a14e60deb860591933381dfeae14d5bbc62ee2849ced84bbed214d716c65ddf1344d82eae199b0dcc04e5248826114c6016b37d15237f31eda966dfdf6b4b76260eef907fb80a67834a829467d608e5fbe1d0a19be89ae9577905b25e0242f8f6e12ddb63b95a86b20cc5b6b7198b6337dd6d6413097d20f6870728b54190627eadd1a87f800004a8ad537f4cde76e0f42f421a7d07856b9b30d18ad166f2905bdd543e34dcf91f0a25122c406fa0d5437526c51b4ef33c8ba6a0c94217fa3e73158b0a039bbe048228c626088553513c93bd816b01518c138d092d03c9bb34419f016282998d525e686abd07b679dd44f8a7ff085f77130ab6c89a879e19c5920980be6c49489f6c0d5742e05884c807cc102beb5f12863804f978c07f90dd8b747e1e3c19e8d269263770751289b76836ce20fe86fec4de4681f1b4322c13d9ce7aafc8ceda1e1f510e593b21602b2b30f57a0bf48db2eefdde0da414d7788a55aa8d2455f5e2b56e403ddd8c0b901a0567e30abdcde3592fbbb21070ee4cf825e96d8efe3e19d9276674fd277d45b510eb60e00ced3feae72227109e3b88ea9cc7b7578d32139b842dd8dee8647e396e2072106caa646eb9bff78995050ffd84e3b1a7685c9fd8ace00047a12b6093f185b4c7d472a71f43102e553a0e566cdd0f49ad93028fbbde26c11a7e5180db2c492df010aa1faef23bf97b26c1e2be498f7066be5ef6fb73d3a6d2e8c1b67734971b352434d3494659a648e0cbb12d03a9c14fd64e950e3e4d6d59d7a89a55a147e365b05ad9c622e6209d73b5f504188fad8bfe082ebbb3d144cf3e85e9b3c74fd565d252c471d3d94cad76bdcabc3b793b147ab367f727fc01038955b8ce089dbb2ae1220c4553278d740e83240fa467c9f4e54e6332c2438970c4a7ceda276d28954ac2bba5782d29a723ef8f34f0b4ea11a9df3082a195c635031386a2339419230fa9e047957af536642f0e7
Parsing Hashes: 0/1 (0.00%)...No hashes loaded.

Started: Thu Jul 13 00:28:15 2017
Stopped: Thu Jul 13 00:28:17 2017

**Comment by philsmd** [comment]
Well, I would need a full example to troubleshoot this.

The "hash" above is not the full hash it doesn't include the last 2 fields.

If possible, the full .7z file + the output of 7z2hashcat.pl (including warnings/errors) would help to understand the problem here.

You also always should make sure (and mention) the version numbers of hashcat and of 7z2hashcat.
Older version of either one or the other tool might not work together correctly, i.e. both hashcat and 7z2hashcat need to be up to date.

**Comment by philsmd** [comment]
Since I didn't get any answer here and I am quite sure that this is just a problem of an older version you were running, I will close this issue for now (feel free to reopen if you still experience some problems and are able to give more details about it).

I also released an up-to-date executable version (https://github.com/philsmd/7z2hashcat/releases/tag/1.1), just to make sure that windows users do not run too old versions of 7z2hashcat.

Thanks
