### ISSUE TITLE
Hide the ecnrypted data in the output

### ISSUE THREAD

**Issue by Setplus01** [philsmd/7z2hashcat#17]
I need some help. Can somebody help me to find and comment commands in the code in a way to hide the encrypted data from the output of this programm? Thank you.

P.S. Veeeery usefull tool, thanks a lot for it!

**Comment by philsmd** [comment]
it's not possible to hide the important information from the output.

the crackers (e.g. hashcat) needs this information to be able to verify that the decrypted and decompressed data matches the checksum.

This is unfortunately how the verification of the passwords works for 7-Zip archives. You need the data to be able to say if the password is correct or if it isn't.
