### ISSUE TITLE
Where does the output.hash end up?

### ISSUE THREAD

**Issue by level42ca** [philsmd/7z2hashcat#18]
I have a 250mb .7z file, and when I run this, I get a massive! hash output in the command line, and then nothing.

Tried both the pre-compiled windows version, and running it on Ubuntu.

**Comment by philsmd** [comment]
It seems (at least if this user is you) that you already figured out how to save the output into a file: https://hashcat.net/forum/thread-7378.html

In general you can just use the command line redirect operator "> hash.txt" to redirect the output of 7z2hashcat to the file hash.txt

**Comment by level42ca** [comment]
I did figure that out, but only after I copy and pasted it out of the command window. Thanks for the update :)
