### ISSUE TITLE
Data length too long?

### ISSUE THREAD

**Issue by hplc** [philsmd/7z2hashcat#30]
While trying to exact hash from a large 7zip file (>3GB), it says:
```
WARNING: the file '../test.7z' unfortunately can't be used with hashcat since the data length
in this particular case is too long (3103387920 of the maximum allowed 327528 bytes).
```

**Comment by philsmd** [comment]
the problem unfortunately is that hashcat has this maximum data length size (almost exactly 320 KiB).

but your file is also very, very huge, 3103387920 is over 2 GiB large, that's just insane... hashcat would need to decrypt and decompress all the data all the time for each and every key it tries... It's not supported by the other tool (hashcat)
