### ISSUE TITLE
Unsupported file

### ISSUE THREAD

**Issue by sawft99** [philsmd/7z2hashcat#36]
I attempted to run on windows with release but I get an error saying it is not supported. Originally created as a password protect zip. Renamed to .7z and still not working.

**Comment by philsmd** [comment]
Hey,

`zip` files are not supported, you need to use `zip2john` or similar tools for `winzip` (also `pkzip`, `securezip` are completely different).

You can't just rename the files. The data is different and `7z2hashcat` is not intended to use on other/normal `zip` files (only `.7z`).
