### ISSUE TITLE
Use existing first "0" field for telling that LZMA / LZMA2 decompression is needed before CRC

### ISSUE THREAD

**Issue by magnumripper** [philsmd/7z2hashcat#4]
Background: https://hashcat.net/forum/thread-4328-post-32963.html#pid32963

Good job on finding out what we were missing!

I'm not sure of the original idea with the zero in `$7z$0$...` but it's not used anywhere so I'm pretty sure we can use it as a flag field. This will ensure backward compatibility in a good way - eg. hashes that set LZMA won't be loaded by a version of JtR or Hashcat that doesn't support it (at least that's true for JtR, I didn't look at HC yet).

So I propose we use this field with `$7z$1$...` meaning LZMA, and `$7z$2$...` meaning LZMA2.

Att: @jsteube and @kholia

**Comment by philsmd** [comment]
That's interesting... I had exactly the same idea while troubleshooting the problem and writing the post on hashcat's forum... but I wanted to make sure that this field had no additional meaning (that I wasn't aware of).

Yeah, I will update 7z2hashcat.pl soon.

**Comment by philsmd** [comment]
I think that this updated hash format solves the problem (of the lack of the compression information mentioned on hashcat's forum).
Now it's the time for the crackers to implement/support this.

Close?

**Comment by magnumripper** [comment]
Perfect! So now I've got work to do in JtR.
