### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by omareltf** [philsmd/7z2hashcat#40]
Virus Total is saying that the release you published (1.9) is contacting several IP addresses, why does it need to do that?

https://www.virustotal.com/gui/file/d6d2828009d8a4dbb3416b4fa16e1db7ea02408dd5d0cdea71e5ab9e9474a028/relations

**Comment by philsmd** [comment]
I'm pretty sure that this is a false positive, there are some anti-virus software out there that just assume something one day and when you contact them, you get the answer that it was a wrong result (and they hopefully will fix it).

All the software is open source here and you can just look at the code.

Do you know this vendor "SecureAge" ? I've never heard of this. I'm pretty sure this is just a **false positive**. The code is very straight forward and everything is open source. You could even built your own releases with the perl packer and try to upload them and contact the anti-virus/malware software vendor.

Thanks
