### ISSUE TITLE
LZMA.pm not found

### ISSUE THREAD

**Issue by TravelNVal38** [philsmd/7z2hashcat#41]
Think may be a recurring issue for people but haven't found a solution. I have done all of these, and yet I still get an error that can not find LZMA.PM in @INC error.

Done the below.
```
sudo cpan Compress::Raw::Lzma
cpan Compress::Raw::Lzma
sudo cpan IO::Compress::Lzma
cpan IO::Compress::Lzma
```

Error
Can't locate Compress/Raw/Lzma.pm in @INC (you may need to install the Compress::Raw::Lzma module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at 7z2hashcat.pl line 6.

**Comment by philsmd** [comment]
Seems to be a local problem on your system. Maybe you have different versions of perl/cpan installed that do have conflicts or you install the modules with one version of perl, but not the other one that you are finally invoking/running.

Maybe you should test it on a different system/PC, just to make sure it should work as intended.


You  could also try to invoke cpan directly with somethink like `perl -MCPAN -e shell`

try also `perl --version` or installing the module with packages from your distro (apt-get):

```
sudo apt-get install libcompress-raw-lzma-perl
```

and/or:

```
sudo perl -MCPAN -e 'install Compress::Raw::Lzma'
```
