### ISSUE TITLE
No devices found/left.

### ISSUE THREAD

**Issue by tomasalias** [philsmd/7z2hashcat#47]
ATTENTION: the hashes might contain sensitive encrypted data. Be careful when sharing or posting these hashes
hashcat (v6.2.5) starting

No devices found/left.

Started: Sun May 12 16:08:12 2024
Stopped: Sun May 12 16:08:12 2024

**Comment by philsmd** [comment]
This problem has nothing to do with the `7z2hashcat` tools. You need to setup your system correctly for the password recovery software that you use, in your case you need to fix your GPU drivers for the use with the 3rd party tool `hashcat`.
