### ISSUE TITLE
new hash format needed to output additional fields for LZMA/LZMA2 compressed data ($7z$1$ and $7z$2$)

### ISSUE THREAD

**Issue by philsmd** [philsmd/7z2hashcat#6]
There is some discussion going on hashcat's github issue page about the additional data we need for cracking 7z  "hashes" that hold data compressed-before-encrypt.
See: https://github.com/hashcat/hashcat/issues/965#issuecomment-272499461

The current suggestion is to just add 3 new fields after the current format (which is ending with $[data]):
- length of the uncompressed data
- length of the first "stream"
- coder attributes (e.g. lc, pb, lp and the dicSize in case of LZMA1 or dicSize in case of LZMA2)

The current idea also is to not change the format whenever $7z$0$ hashes are outputted (for backwards compatibility?).

Any suggestions are very welcome.

**Comment by magnumripper** [comment]
Are you sure we need both lengths? Let's call them inflated_len and crc_len. Shouldn't we be fine with just crc_len and inflate the data using LZMA_FINISH_ANY?

**Comment by magnumripper** [comment]
I think the comments in LzmaDec.h support my theory, eg:
```c
/* There are two types of LZMA streams:
     0) Stream with end mark. That end mark adds about 6 bytes to compressed size.
     1) Stream without end mark. You must know exact uncompressed size to decompress such stream. */

typedef enum
{
  LZMA_FINISH_ANY,   /* finish at any point */
  LZMA_FINISH_END    /* block must be finished at the end */
} ELzmaFinishMode;

/* ELzmaFinishMode has meaning only if the decoding reaches output limit !!!

   You must use LZMA_FINISH_END, when you know that current output buffer
   covers last bytes of block. In other cases you must use LZMA_FINISH_ANY.

   If LZMA decoder sees end marker before reaching output limit, it returns SZ_OK,
   and output value of destLen will be less than output buffer size limit.
   You can check status result also.

   You can use multiple checks to test data integrity after full decompression:
     1) Check Result and "status" variable.
     2) Check that output(destLen) = uncompressedSize, if you know real uncompressedSize.
     3) Check that output(srcLen) = compressedSize, if you know real compressedSize.
        You must use correct finish mode in that case. */
```
In all my tests I ended up with SZ_OK and "output(destLen) = uncompressedSize" as expressed above (while "output(srcLen)" was way lower than "compressedSize").

This opens up another possibility, at least for Hashcat. I regard the input line length limit of 768 bytes in HC as a real problem, especially when padding margin is zero or small enough to result in lots of FP. But if we don't actually store the whole compressed data (eg. 436 KB) but instead just enough to be sure we can decompress crc_len (eg. 82 bytes), we're set. So we can truncate this data if we want to - BUT then we instead can't do any padding check unless we extend the ciphertext format even more. Another problem is we can only guess how much we can truncate to get crc_len. In most cases, a truncation to `crc_len * 1.1` should be more than enough.

To still be able to check padding, we'd need BOTH types of truncation, eg. (concept):
```
$7z$x$ salt'n'stuff $ crc $ trunc. iv $ last 16 bytes $ crc_len $ real iv $ first nn bytes
```
This is starting to get too complex though. Also, I see many files where crc_len exceeds 768. I'd rather work around the line length limit in Hashcat. JtR has virtually no limit nowadays - the filesystem and/or OS sets the limit.

**Comment by philsmd** [comment]
It would be great if you could help me verify if the newest version and especially commit https://github.com/philsmd/7z2hashcat/commit/8ef8f21135e5e19bf9614355ef86d3dc248ad4e9 fixed this problem too.
Thank you very much @magnumripper

**Comment by magnumripper** [comment]
Yep. I mentioned a warning in https://github.com/philsmd/7z2hashcat/issues/7#issuecomment-273207929 that might have been better in this issue. Other than that warning, everything seems fine.

Good stuff!

**Comment by philsmd** [comment]
I think now we can close this issue too since the new hash format was implemented and some format details were added also to the .pl script and the README.md.

Thanks
